openapi: 3.0.0

info:
  title: Taskker API
  description: Taskker API
  version: "1.0.0"

tags:
  - name: tasks

paths:
  /tasks:
    get:
      tags:
        - tasks
      summary: get all available tasks
      description: Retrieve Tasks
      parameters:
        - in: query
          name: searchString
          description: pass an optional search string for looking up inventory
          required: false
          schema:
            type: string
        - in: query
          name: skip
          description: number of records to skip for pagination
          schema:
            type: integer
            format: int32
            minimum: 0
        - in: query
          name: limit
          description: maximum number of records to return
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 50
      responses:
        '200':
          description: Tasks results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

components:
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - done
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        title:
          type: string
          example: make managing tasks great again
        description:
          type: string
          example: this is my wonderfull task
        done:
          type: boolean
          example: false
